# List of languages supported by Chared
# Created 20. jan 2014
# by dane22, a Plex community member.
# Feel free to use this file elsewhere, but do tell me about updates to it!!!
#
# TO DO: Fix entries that is remarked

CharedSupported = {
    "ar": "arabic",
    "hy": "armenian",
    "bn": "bengali",
    "bg": "bulgarian",
    "ca": "catalan",
    # "chinese_simplified",
    # "chinese_traditional",
    "hr": "croatian",
    "cs": "czech",
    "nl": "dutch",
    "en": "english",
    "et": "estonian",
    "fi": "finnish",
    "fr": "french",
    "de": "german",
    "el": "greek",
    "gu": "gujarati",
    "he": "hebrew",
    "hi": "hindi",
    "hu": "hungarian",
    "is": "icelandic",
    "id": "indonesian",
    "ga": "irish",
    "it": "italian",
    "ja": "japanese",
    "ko": "korean",
    "lv": "latvian",
    "lt": "lithuanian",
    "ms": "malay",
    "ml": "malayalam",
    "mt": "maltese",
    # "norwegian_bokmal",
    "fa": "persian",
    "pl": "polish",
    "pt": "portuguese",
    "ro": "romanian",
    "ru": "russian",
    "sr": "serbian",
    "sk": "slovak",
    "sl": "slovene",
    "es": "spanish",
    "sv": "swedish",
    "ta": "tamil",
    "te": "telugu",
    "th": "thai",
    # "turkish",
    "uk": "ukrainian",
    "ur": "urdu",
    "vi": "vietnamese",
    "cy": "welsh"
}
